// <auto-generated />
using System;
using AionOverdose58.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AionOverdose58.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412122829_SyncPendingChanges")]
    partial class SyncPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AionOverdose58.Shared.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviewContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("AionOverdose58.Shared.Models.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "AionOverdose Staff",
                            Content = "# Aion 2 Early Access Begins\n\nThe wait is finally over. After years of anticipation, **Aion 2** has officially entered Early Access...\n\nNew mechanics, new classes, and a reimagined Abyss await brave Daevas willing to forge their legend.",
                            ImageUrl = "https://picsum.photos/800/450?random=10",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 3, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "aion2-early-access-begins",
                            Summary = "The gates of the Abyss have opened. Early access to Aion 2 is now live, bringing sweeping new mechanics, redesigned classes, and breathtaking visuals to the eternal conflict between Elyos and Asmodians.",
                            Title = "Aion 2 Early Access Begins — The Eternal Sky Awakens"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "AionOverdose Staff",
                            Content = "# Shadow Reaper — Class Overview\n\nThe **Shadow Reaper** is a fearsome Asmodian-aligned class that blends melee ferocity with dark magic...\n\nExpect high burst damage, stealth mechanics, and a unique soul-harvest resource system.",
                            ImageUrl = "https://picsum.photos/800/450?random=11",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 2, 28, 14, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "shadow-reaper-class-reveal",
                            Summary = "NCSoft reveals the devastating Shadow Reaper — a dark melee-ranged hybrid class wielding twin soul-swords. Master the shadows and harvest the life force of your enemies.",
                            Title = "New Class Reveal: The Shadow Reaper Joins the Battle"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "AionOverdose Staff",
                            Content = "# Patch 1.3 — Balance & Maintenance\n\n## Schedule\nMaintenance window: **Saturday 02:00 – 06:00 UTC**\n\n## Highlights\n- Gladiator: Templar Shield Stun duration reduced\n- Ranger: Bow Skills damage increased by 8%\n- Abyss Point rewards increased for Fortress participation",
                            ImageUrl = "https://picsum.photos/800/450?random=12",
                            IsPublished = true,
                            PublishedAt = new DateTime(2025, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "server-maintenance-balance-patch-1-3",
                            Summary = "Scheduled maintenance on Saturday — patch 1.3 brings critical balance changes to PvP combat, Abyss point rewards, and Fortress siege timers across all servers.",
                            Title = "Server Maintenance & Balance Patch 1.3 Notes"
                        });
                });

            modelBuilder.Entity("AionOverdose58.Shared.Models.PlayerRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlayerRankings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "Gladiator",
                            Level = 65,
                            PlayerName = "DarkWingDaeva",
                            Rank = 1,
                            Score = 1250000L,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Class = "Ranger",
                            Level = 65,
                            PlayerName = "SkyBlazer",
                            Rank = 2,
                            Score = 1180500L,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Class = "Sorcerer",
                            Level = 65,
                            PlayerName = "AbyssQueen",
                            Rank = 3,
                            Score = 1050200L,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Class = "Templar",
                            Level = 64,
                            PlayerName = "IronTemplar",
                            Rank = 4,
                            Score = 987300L,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Class = "Assassin",
                            Level = 63,
                            PlayerName = "StormChaser",
                            Rank = 5,
                            Score = 912750L,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AionOverdose58.Shared.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("AionOverdose58.Shared.Models.WikiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("WikiEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Beginner",
                            Content = "# Getting Started\n\nWelcome to Aion 2! This guide will help new Daevas find their wings...",
                            Slug = "getting-started",
                            Title = "Getting Started in Aion 2",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Classes",
                            Content = "# Gladiator\n\nThe Gladiator is the frontline warrior of the Elyos faction...",
                            Slug = "gladiator-class-guide",
                            Title = "Gladiator Class Guide",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "PvP",
                            Content = "# Abyss PvP Guide\n\nThe Abyss is the central battleground between Elyos, Asmodians, and the Balaur...",
                            Slug = "abyss-pvp-guide",
                            Title = "Abyss PvP Guide",
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
